name: Node.js CI  # Workflow name

on:
  push:
    branches:
      - main  # Trigger workflow when pushing to main branch
  pull_request:
    branches:
      - main  # Trigger workflow on pull requests to main branch

jobs:
  build:
    runs-on: ubuntu-latest  # The environment where the job will run

    steps:
      - name: Checkout code  # Step 1: Get the latest code from GitHub
        uses: actions/checkout@v2

      - name: Set up Node.js  # Step 2: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies  # Step 3: Install project dependencies
        run: npm install

      - name: Run tests  # Step 4: Run tests
        run: npm test
        

